import type { NodeType } from "../../store/useProjectStore";

export const NODE_IMPLEMENTATION_NOTES: Partial<Record<NodeType, string>> = {
  physicsSolver: "Performs structural analysis using finite element methods, calculating how structures respond to loads. The solver assembles a stiffness matrix from mesh geometry and material properties, applies boundary conditions (anchors) and loads, then solves the equilibrium equation Kd = F to find displacements. From displacements, it derives stress and strain fields throughout the structure. Connect mesh geometry to the baseMesh input, wire Goal nodes for loads (forces) and anchors (fixed supports), optionally add stiffness and volume goals for optimization. Outputs include the deformed mesh (showing structural deflection), stress field (where material is working hardest), displacement vectors, and diagnostic data. Physics Solver is the core tool for structural validation—checking that designs can carry their loads—and for form-finding where structure shapes itself optimally.",
  
  voxelSolver: "Converts geometry into a uniform voxel grid representation—a 3D array of cubic cells where each cell is either filled (occupied by geometry) or empty. Input any geometry and specify the resolution (number of voxels along the longest axis). The voxelizer samples the input geometry to determine which cells intersect it, then performs flood-fill to identify interior vs exterior regions. Outputs include the voxel grid data structure (for computational operations), a blocky mesh visualization (for rendering), and statistics (cell count, filled count, fill ratio). Voxelization is fundamental for volumetric operations: converting continuous geometry into discrete cells enables grid-based simulations, boolean operations on complex topology, and uniform spatial sampling. Use Voxel Solver when you need to discretize geometry for computational analysis or when you want a blocky, Minecraft-style aesthetic.",
  
  chemistrySolver: "Implements multi-material optimization through particle-based simulation—a paradigm inspired by physical chemistry where different material species diffuse, react, and compete for space. Unlike single-material topology optimization (which decides where material exists), chemistry optimization decides which material belongs where. Define available materials with Chemistry Material Goal nodes, specify material seeds (starting regions), and add property goals (stiffness, mass, transparency, thermal). The solver simulates particles of different species diffusing through the domain, with energetic goals driving material concentrations toward optimal configurations. The result is functionally graded materials—smooth transitions from steel to ceramic to glass, optimized for structural performance, thermal behavior, or optical transmission. This enables designing multi-physics components impossible with discrete material assignments.",
  
  evolutionarySolver: "Searches design parameters using evolutionary optimization to improve objectives. This genetic algorithm-based solver evolves a population of design candidates through selection, crossover, and mutation operations. Each individual in the population represents a set of parameter values that define a geometry configuration. The solver evaluates fitness (how well each design meets objectives), selects the best performers as parents, combines their parameters through crossover, and introduces random mutations to explore new possibilities. Over many generations, the population converges toward optimal solutions. Configure population size, mutation rate, crossover rate, and selection method to balance exploration (finding diverse solutions) versus exploitation (refining known good solutions). Use Evolutionary Solver when the design space is complex, non-convex, or when you want to discover unexpected solutions that gradient-based methods might miss.",
  
  topologyOptimizationSolver: "Optimizes material distribution within a design space subject to loads and constraints. This solver determines where material should exist to maximize structural performance while minimizing mass. Starting with a solid domain, the solver iteratively removes material from low-stress regions and adds material to high-stress regions, guided by sensitivity analysis. The volume fraction parameter controls how much material remains (0.3 = 30% of original volume). The penalty exponent (typically 3.0) ensures the solution converges to solid/void rather than intermediate densities. Filter radius controls feature size—larger values produce smoother, more manufacturable results. Topology optimization reveals the optimal load paths through a structure, often producing organic, bone-like forms that are both lightweight and strong. Use this solver for structural design where you know the loads and supports but want to discover the ideal material layout.",
};
