/**
 * Auto-generated comprehensive documentation
 * Generated by scripts/generateComprehensiveDocumentation.ts
 * 
 * DO NOT EDIT MANUALLY - regenerate using:
 * npm run generate:docs
 */

export const COMMAND_DOCUMENTATION = {
  "point": {
    "label": "Point",
    "category": "geometry",
    "description": "Point: click to place a point. Esc cancels.",
    "semanticOps": [
      "command.createPoint"
    ],
    "semanticOpDescriptions": [
      "Create Point: Creates a point at a clicked location"
    ]
  },
  "box": {
    "label": "Box",
    "category": "geometry",
    "description": "Box: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "sphere": {
    "label": "Sphere",
    "category": "geometry",
    "description": "Sphere: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "cylinder": {
    "label": "Cylinder",
    "category": "geometry",
    "description": "Cylinder: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "torus": {
    "label": "Torus",
    "category": "geometry",
    "description": "Torus: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "pyramid": {
    "label": "Pyramid",
    "category": "geometry",
    "description": "Pyramid: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "tetrahedron": {
    "label": "Tetrahedron",
    "category": "geometry",
    "description": "Tetrahedron: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "octahedron": {
    "label": "Octahedron",
    "category": "geometry",
    "description": "Octahedron: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "icosahedron": {
    "label": "Icosahedron",
    "category": "geometry",
    "description": "Icosahedron: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "dodecahedron": {
    "label": "Dodecahedron",
    "category": "geometry",
    "description": "Dodecahedron: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "hemisphere": {
    "label": "Hemisphere",
    "category": "geometry",
    "description": "Hemisphere: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "capsule": {
    "label": "Capsule",
    "category": "geometry",
    "description": "Capsule: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "disk": {
    "label": "Disk",
    "category": "geometry",
    "description": "Disk: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "ring": {
    "label": "Ring / Annulus",
    "category": "geometry",
    "description": "Ring / Annulus: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "triangular-prism": {
    "label": "Triangular Prism",
    "category": "geometry",
    "description": "Triangular Prism: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "hexagonal-prism": {
    "label": "Hexagonal Prism",
    "category": "geometry",
    "description": "Hexagonal Prism: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "pentagonal-prism": {
    "label": "Pentagonal Prism",
    "category": "geometry",
    "description": "Pentagonal Prism: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "torus-knot": {
    "label": "Torus Knot",
    "category": "geometry",
    "description": "Torus Knot: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "utah-teapot": {
    "label": "Utah Teapot",
    "category": "geometry",
    "description": "Utah Teapot: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "frustum": {
    "label": "Frustum",
    "category": "geometry",
    "description": "Frustum: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "mobius-strip": {
    "label": "Mobius Strip",
    "category": "geometry",
    "description": "Mobius Strip: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "ellipsoid": {
    "label": "Ellipsoid",
    "category": "geometry",
    "description": "Ellipsoid: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "wedge": {
    "label": "Wedge",
    "category": "geometry",
    "description": "Wedge: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "spherical-cap": {
    "label": "Spherical Cap / Dome",
    "category": "geometry",
    "description": "Spherical Cap / Dome: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "bipyramid": {
    "label": "Bipyramid",
    "category": "geometry",
    "description": "Bipyramid: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "rhombic-dodecahedron": {
    "label": "Rhombic Dodecahedron",
    "category": "geometry",
    "description": "Rhombic Dodecahedron: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "truncated-cube": {
    "label": "Truncated Cube",
    "category": "geometry",
    "description": "Truncated Cube: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "truncated-octahedron": {
    "label": "Truncated Octahedron",
    "category": "geometry",
    "description": "Truncated Octahedron: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "truncated-icosahedron": {
    "label": "Truncated Icosahedron",
    "category": "geometry",
    "description": "Truncated Icosahedron: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "pipe": {
    "label": "Pipe / Hollow Cylinder",
    "category": "geometry",
    "description": "Pipe / Hollow Cylinder: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "superellipsoid": {
    "label": "Superellipsoid",
    "category": "geometry",
    "description": "Superellipsoid: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "hyperbolic-paraboloid": {
    "label": "Hyperbolic Paraboloid",
    "category": "geometry",
    "description": "Hyperbolic Paraboloid: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "geodesic-dome": {
    "label": "Geodesic Dome",
    "category": "geometry",
    "description": "Geodesic Dome: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "one-sheet-hyperboloid": {
    "label": "One-Sheet Hyperboloid",
    "category": "geometry",
    "description": "One-Sheet Hyperboloid: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createPrimitive"
    ],
    "semanticOpDescriptions": [
      "Create Primitive: Creates a mesh primitive (box, sphere, cylinder, etc.)"
    ]
  },
  "line": {
    "label": "Line",
    "category": "geometry",
    "description": "Line: click start, click end to place a segment. Double-click to finish. Esc cancels.",
    "semanticOps": [
      "command.createLine"
    ],
    "semanticOpDescriptions": [
      "Create Line: Creates straight line segments"
    ]
  },
  "polyline": {
    "label": "Polyline",
    "category": "geometry",
    "description": "Polyline: click points to draw. Right-click or double-click to finish. Esc cancels.",
    "semanticOps": [
      "command.createPolyline"
    ],
    "semanticOpDescriptions": [
      "Create Polyline: Creates a connected sequence of straight segments"
    ]
  },
  "rectangle": {
    "label": "Rectangle",
    "category": "geometry",
    "description": "Rectangle: click first corner, click opposite corner to place. Esc cancels.",
    "semanticOps": [
      "command.createRectangle"
    ],
    "semanticOpDescriptions": [
      "Create Rectangle: Creates a four-sided closed polyline with right-angle corners"
    ]
  },
  "circle": {
    "label": "Circle",
    "category": "geometry",
    "description": "Circle: click center, click radius to place. Esc cancels.",
    "semanticOps": [
      "command.createCircle"
    ],
    "semanticOpDescriptions": [
      "Create Circle: Creates a perfect circular NURBS curve"
    ]
  },
  "arc": {
    "label": "Arc",
    "category": "geometry",
    "description": "Arc: click start, click end, click a point on the arc. Double-click to finish. Esc cancels.",
    "semanticOps": [
      "command.createArc"
    ],
    "semanticOpDescriptions": [
      "Create Arc: Creates a circular arc segment using three-point definition"
    ]
  },
  "curve": {
    "label": "Curve",
    "category": "geometry",
    "description": "Curve: click points to shape the curve. Right-click or double-click to finish. Esc cancels.",
    "semanticOps": [
      "command.createCurve"
    ],
    "semanticOpDescriptions": [
      "Create Curve: Creates a freeform NURBS curve influenced by control points"
    ]
  },
  "nurbsbox": {
    "label": "NURBS Box",
    "category": "geometry",
    "description": "NURBS Box: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createNurbsBox"
    ],
    "semanticOpDescriptions": [
      "Create NURBS Box: Creates a box primitive using NURBS surface representation"
    ]
  },
  "nurbssphere": {
    "label": "NURBS Sphere",
    "category": "geometry",
    "description": "NURBS Sphere: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createNurbsSphere"
    ],
    "semanticOpDescriptions": [
      "Create NURBS Sphere: Creates a sphere using exact NURBS surface definition"
    ]
  },
  "nurbscylinder": {
    "label": "NURBS Cylinder",
    "category": "geometry",
    "description": "NURBS Cylinder: click to set base on the C-Plane, move to size, click to place. Esc cancels.",
    "semanticOps": [
      "command.createNurbsCylinder"
    ],
    "semanticOpDescriptions": [
      "Create NURBS Cylinder: Creates a cylinder using exact NURBS surface definition"
    ]
  },
  "meshconvert": {
    "label": "NURBS to Mesh",
    "category": "performs",
    "description": "NURBS to Mesh: select NURBS curves or surfaces, then click Run or press Enter.",
    "semanticOps": [
      "command.meshConvert"
    ],
    "semanticOpDescriptions": [
      "NURBS to Mesh: Converts NURBS curves or surfaces to mesh"
    ]
  },
  "breptomesh": {
    "label": "B-Rep to Mesh",
    "category": "performs",
    "description": "B-Rep to Mesh: select B-Rep solids, then click Run or press Enter.",
    "semanticOps": [
      "command.brepToMesh"
    ],
    "semanticOpDescriptions": [
      "B-Rep to Mesh: Converts B-Rep solids to mesh"
    ]
  },
  "meshtobrep": {
    "label": "Mesh to B-Rep",
    "category": "performs",
    "description": "Mesh to B-Rep: select meshes, then click Run or press Enter.",
    "semanticOps": [
      "command.meshToBrep"
    ],
    "semanticOpDescriptions": [
      "Mesh to B-Rep: Converts meshes to B-Rep solids"
    ]
  },
  "nurbsrestore": {
    "label": "Mesh to NURBS",
    "category": "performs",
    "description": "Mesh to NURBS: select a mesh converted from NURBS, then click Run or press Enter.",
    "semanticOps": [
      "command.nurbsRestore"
    ],
    "semanticOpDescriptions": [
      "Mesh to NURBS: Restores NURBS from a mesh converted from NURBS"
    ]
  },
  "interpolate": {
    "label": "Interpolate",
    "category": "performs",
    "description": "Interpolate: select polylines, then click Run or press Enter to convert.",
    "semanticOps": [
      "command.interpolate"
    ],
    "semanticOpDescriptions": [
      "Interpolate: Converts polyline to smooth NURBS curve passing through vertices"
    ]
  },
  "boolean": {
    "label": "Boolean",
    "category": "performs",
    "description": "Boolean: select solids, then click Run to combine. Esc cancels.",
    "semanticOps": [
      "command.boolean"
    ],
    "semanticOpDescriptions": [
      "Boolean: Performs Boolean operations (union, difference, intersection) on solids"
    ]
  },
  "loft": {
    "label": "Loft",
    "category": "performs",
    "description": "Loft: select two or more curves, then click Run or press Enter. Esc cancels.",
    "semanticOps": [
      "command.loft"
    ],
    "semanticOpDescriptions": [
      "Loft: Creates a surface by lofting through two or more curves"
    ]
  },
  "surface": {
    "label": "Surface",
    "category": "performs",
    "description": "Surface: select a closed curve, then click Run or press Enter. Esc cancels.",
    "semanticOps": [
      "command.surface"
    ],
    "semanticOpDescriptions": [
      "Surface: Creates a surface from a closed curve"
    ]
  },
  "extrude": {
    "label": "Extrude",
    "category": "performs",
    "description": "Extrude: select a profile, then drag to set distance or enter a value.",
    "semanticOps": [
      "command.extrude"
    ],
    "semanticOpDescriptions": [
      "Extrude: Extrudes a profile along a direction to create a solid"
    ]
  },
  "meshmerge": {
    "label": "Mesh Merge",
    "category": "performs",
    "description": "Mesh Merge: select meshes, then click Run or press Enter to combine.",
    "semanticOps": [
      "command.meshMerge"
    ],
    "semanticOpDescriptions": [
      "Mesh Merge: Merges multiple meshes into a single mesh"
    ]
  },
  "meshflip": {
    "label": "Mesh Flip",
    "category": "performs",
    "description": "Mesh Flip: select meshes, then click Run or press Enter to flip normals.",
    "semanticOps": [
      "command.meshFlip"
    ],
    "semanticOpDescriptions": [
      "Mesh Flip: Flips mesh normals (reverses face orientation)"
    ]
  },
  "meshthicken": {
    "label": "Mesh Thicken",
    "category": "performs",
    "description": "Mesh Thicken: select meshes, set thickness/sides, then click Run or press Enter.",
    "semanticOps": [
      "command.meshThicken"
    ],
    "semanticOpDescriptions": [
      "Mesh Thicken: Thickens a mesh by offsetting faces along normals"
    ]
  },
  "transform": {
    "label": "Transform",
    "category": "performs",
    "description": "Transform: select geometry, drag gumball handles or enter values.",
    "semanticOps": [
      "command.transform"
    ],
    "semanticOpDescriptions": [
      "Transform: Transforms geometry using gumball widget"
    ]
  },
  "move": {
    "label": "Move",
    "category": "performs",
    "description": "Move: select geometry, drag a gumball handle or enter XYZ values.",
    "semanticOps": [
      "command.move"
    ],
    "semanticOpDescriptions": [
      "Move: Translates geometry by a vector"
    ]
  },
  "rotate": {
    "label": "Rotate",
    "category": "performs",
    "description": "Rotate: select geometry, drag a rotation ring or enter an angle.",
    "semanticOps": [
      "command.rotate"
    ],
    "semanticOpDescriptions": [
      "Rotate: Rotates geometry around an axis"
    ]
  },
  "scale": {
    "label": "Scale",
    "category": "performs",
    "description": "Scale: select geometry, drag a scale handle or enter values.",
    "semanticOps": [
      "command.scale"
    ],
    "semanticOpDescriptions": [
      "Scale: Scales geometry by a factor"
    ]
  },
  "offset": {
    "label": "Offset",
    "category": "performs",
    "description": "Offset: select curves, then click to set distance.",
    "semanticOps": [
      "command.offset"
    ],
    "semanticOpDescriptions": [
      "Offset: Offsets curves by a distance"
    ]
  },
  "mirror": {
    "label": "Mirror",
    "category": "performs",
    "description": "Mirror: select geometry, then click to define the mirror line or plane.",
    "semanticOps": [
      "command.mirror"
    ],
    "semanticOpDescriptions": [
      "Mirror: Mirrors geometry across a plane"
    ]
  },
  "array": {
    "label": "Array",
    "category": "performs",
    "description": "Array: select geometry, then set direction, spacing, and count.",
    "semanticOps": [
      "command.array"
    ],
    "semanticOpDescriptions": [
      "Array: Replicates geometry in a pattern"
    ]
  },
  "gumball": {
    "label": "Gumball",
    "category": "performs",
    "description": "Gumball: click a handle to move/rotate/scale, click again to confirm.",
    "semanticOps": [
      "command.gumball"
    ],
    "semanticOpDescriptions": [
      "Gumball: Activates gumball transform widget"
    ]
  },
  "undo": {
    "label": "Undo",
    "category": "performs",
    "description": "Undo: click or press Cmd/Ctrl+Z to undo the last action.",
    "semanticOps": [
      "command.undo"
    ],
    "semanticOpDescriptions": [
      "Undo: Undoes the last action"
    ]
  },
  "redo": {
    "label": "Redo",
    "category": "performs",
    "description": "Redo: click or press Cmd+Shift+Z or Ctrl+Y.",
    "semanticOps": [
      "command.redo"
    ],
    "semanticOpDescriptions": [
      "Redo: Redoes the last undone action"
    ]
  },
  "copy": {
    "label": "Copy",
    "category": "performs",
    "description": "Copy: click or press Cmd/Ctrl+C to copy selection.",
    "semanticOps": [
      "command.copy"
    ],
    "semanticOpDescriptions": [
      "Copy: Copies selection to clipboard"
    ]
  },
  "paste": {
    "label": "Paste",
    "category": "performs",
    "description": "Paste: click or press Cmd/Ctrl+V. Choose placement: in place, cursor, origin.",
    "semanticOps": [
      "command.paste"
    ],
    "semanticOpDescriptions": [
      "Paste: Pastes from clipboard"
    ]
  },
  "duplicate": {
    "label": "Duplicate",
    "category": "performs",
    "description": "Duplicate: click or press Cmd/Ctrl+D. Alt-drag also duplicates.",
    "semanticOps": [
      "command.duplicate"
    ],
    "semanticOpDescriptions": [
      "Duplicate: Duplicates selection in place"
    ]
  },
  "delete": {
    "label": "Delete",
    "category": "performs",
    "description": "Delete: click or press Delete/Backspace to remove selection.",
    "semanticOps": [
      "command.delete"
    ],
    "semanticOpDescriptions": [
      "Delete: Deletes selection"
    ]
  },
  "cancel": {
    "label": "Cancel",
    "category": "performs",
    "description": "Cancel: click or press Esc to cancel the active command.",
    "semanticOps": [
      "command.cancel"
    ],
    "semanticOpDescriptions": [
      "Cancel: Cancels the active command"
    ]
  },
  "confirm": {
    "label": "Confirm",
    "category": "performs",
    "description": "Confirm: click or press Enter to commit the active command.",
    "semanticOps": [
      "command.confirm"
    ],
    "semanticOpDescriptions": [
      "Confirm: Confirms the active command"
    ]
  },
  "focus": {
    "label": "Focus",
    "category": "performs",
    "description": "Focus: click to frame the current selection.",
    "semanticOps": [
      "command.focus"
    ],
    "semanticOpDescriptions": [
      "Focus: Frames the current selection"
    ]
  },
  "frameall": {
    "label": "Frame All",
    "category": "performs",
    "description": "Frame All: click to frame all visible geometry.",
    "semanticOps": [
      "command.frameAll"
    ],
    "semanticOpDescriptions": [
      "Frame All: Frames all visible geometry"
    ]
  },
  "screenshot": {
    "label": "Screenshot",
    "category": "performs",
    "description": "Screenshot: capture the current Roslyn viewport and open the export preview.",
    "semanticOps": [
      "command.screenshot"
    ],
    "semanticOpDescriptions": [
      "Screenshot: Captures the current viewport"
    ]
  },
  "view": {
    "label": "View",
    "category": "performs",
    "description": "View: click to switch to top/front/right/perspective.",
    "semanticOps": [
      "command.view"
    ],
    "semanticOpDescriptions": [
      "View: Switches to a preset view (top/front/right/perspective)"
    ]
  },
  "camera": {
    "label": "Camera",
    "category": "performs",
    "description": "Camera: click to toggle camera options (zoom to cursor, invert zoom, upright).",
    "semanticOps": [
      "command.camera"
    ],
    "semanticOpDescriptions": [
      "Camera: Toggles camera options"
    ]
  },
  "pivot": {
    "label": "Pivot",
    "category": "performs",
    "description": "Pivot: click a pivot mode, then click a point to place it.",
    "semanticOps": [
      "command.pivot"
    ],
    "semanticOpDescriptions": [
      "Pivot: Sets the pivot point for transformations"
    ]
  },
  "orbit": {
    "label": "Orbit",
    "category": "performs",
    "description": "Orbit: click-drag (right mouse) to orbit the view.",
    "semanticOps": [
      "command.orbit"
    ],
    "semanticOpDescriptions": [
      "Orbit: Orbits the camera around the view center"
    ]
  },
  "pan": {
    "label": "Pan",
    "category": "performs",
    "description": "Pan: click-drag (middle mouse or Shift+right) to pan.",
    "semanticOps": [
      "command.pan"
    ],
    "semanticOpDescriptions": [
      "Pan: Pans the camera"
    ]
  },
  "zoom": {
    "label": "Zoom",
    "category": "performs",
    "description": "Zoom: scroll to zoom in/out. Click to toggle zoom mode.",
    "semanticOps": [
      "command.zoom"
    ],
    "semanticOpDescriptions": [
      "Zoom: Zooms the camera in/out"
    ]
  },
  "selectionfilter": {
    "label": "Selection Filter",
    "category": "performs",
    "description": "Selection Filter: click Object/Vertex/Edge/Face to change picks.",
    "semanticOps": [
      "command.selectionFilter"
    ],
    "semanticOpDescriptions": [
      "Selection Filter: Changes selection filter (object/vertex/edge/face)"
    ]
  },
  "cycle": {
    "label": "Cycle Selection",
    "category": "performs",
    "description": "Cycle: click to cycle overlapping picks (Tab also works).",
    "semanticOps": [
      "command.cycle"
    ],
    "semanticOpDescriptions": [
      "Cycle Selection: Cycles through overlapping selections"
    ]
  },
  "snapping": {
    "label": "Snapping",
    "category": "performs",
    "description": "Snapping: click to toggle grid/vertex/endpoint/midpoint/intersection.",
    "semanticOps": [
      "command.snapping"
    ],
    "semanticOpDescriptions": [
      "Snapping: Toggles snapping modes (grid/vertex/endpoint/midpoint/intersection)"
    ]
  },
  "grid": {
    "label": "Grid",
    "category": "performs",
    "description": "Grid: click to change spacing/units or toggle adaptive grid.",
    "semanticOps": [
      "command.grid"
    ],
    "semanticOpDescriptions": [
      "Grid: Changes grid spacing/units or toggles adaptive grid"
    ]
  },
  "cplane": {
    "label": "C-Plane",
    "category": "performs",
    "description": "C-Plane: click world XY/XZ/YZ or click 3 points to define a plane.",
    "semanticOps": [
      "command.cplane"
    ],
    "semanticOpDescriptions": [
      "C-Plane: Sets the construction plane"
    ]
  },
  "display": {
    "label": "Display",
    "category": "performs",
    "description": "Display: click to switch wireframe/shaded/edges/ghosted/silhouette.",
    "semanticOps": [
      "command.display"
    ],
    "semanticOpDescriptions": [
      "Display: Switches display mode (wireframe/shaded/edges/ghosted/silhouette)"
    ]
  },
  "isolate": {
    "label": "Isolate",
    "category": "performs",
    "description": "Isolate: click to hide/lock selection; click again to show all.",
    "semanticOps": [
      "command.isolate"
    ],
    "semanticOpDescriptions": [
      "Isolate: Hides/locks selection or shows all"
    ]
  },
  "outliner": {
    "label": "Outliner",
    "category": "performs",
    "description": "Outliner: click to manage groups, layers, and visibility.",
    "semanticOps": [
      "command.outliner"
    ],
    "semanticOpDescriptions": [
      "Outliner: Manages groups, layers, and visibility"
    ]
  },
  "tolerance": {
    "label": "Tolerance",
    "category": "performs",
    "description": "Tolerance: click to set absolute and angle tolerance.",
    "semanticOps": [
      "command.tolerance"
    ],
    "semanticOpDescriptions": [
      "Tolerance: Sets absolute and angle tolerance"
    ]
  },
  "status": {
    "label": "Status",
    "category": "performs",
    "description": "Status: click to toggle command help/status bar.",
    "semanticOps": [
      "command.status"
    ],
    "semanticOpDescriptions": [
      "Status: Toggles command help/status bar"
    ]
  },
  "morph": {
    "label": "Morph",
    "category": "performs",
    "description": "Morph: select geometry, then click-drag to sculpt. Esc cancels.",
    "semanticOps": [
      "command.morph"
    ],
    "semanticOpDescriptions": [
      "Morph: Sculpts geometry by dragging vertices"
    ]
  }
} as const;
