/**
 * Script to generate semanticOpIds.ts from all semantic operation definitions
 */

const fs = require('fs');
const path = require('path');

// Read all operation files and extract IDs
const opsDir = path.join(__dirname, '..', 'client', 'src', 'semantic', 'ops');
const files = fs.readdirSync(opsDir).filter(f => f.endsWith('Ops.ts') && f !== 'index.ts');

const allOpIds = [];

for (const file of files) {
  const content = fs.readFileSync(path.join(opsDir, file), 'utf8');
  const idMatches = content.matchAll(/id: '([^']+)'/g);
  for (const match of idMatches) {
    allOpIds.push(match[1]);
  }
}

// Also get geometry operation IDs
const geometryFiles = [
  'meshOps.ts',
  'meshTessellationOps.ts',
  'mathOps.ts',
  'curveOps.ts',
  'booleanOps.ts',
  'brepOps.ts',
  'tessellationOps.ts'
];

for (const file of geometryFiles) {
  const filePath = path.join(__dirname, '..', 'client', 'src', 'geometry', file);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    const idMatches = content.matchAll(/id: '([^']+)'/g);
    for (const match of idMatches) {
      if (!allOpIds.includes(match[1])) {
        allOpIds.push(match[1]);
      }
    }
  }
}

// Sort IDs
allOpIds.sort();

// Generate semanticOpIds.ts
const content = `/**
 * Semantic operation IDs
 * 
 * This file contains all valid semantic operation IDs used throughout Lingua.
 * It provides compile-time type safety for operation references.
 * 
 * Auto-generated by scripts/generateSemanticOpIds.js
 * DO NOT EDIT MANUALLY
 */

export const SEMANTIC_OP_IDS = [
${allOpIds.map(id => `  '${id}'`).join(',\n')}
] as const;

export type SemanticOpId = typeof SEMANTIC_OP_IDS[number];

export const SEMANTIC_OP_ID_SET = new Set<string>(SEMANTIC_OP_IDS);

export function isValidSemanticOpId(id: string): id is SemanticOpId {
  return SEMANTIC_OP_ID_SET.has(id);
}
`;

const outputPath = path.join(__dirname, '..', 'client', 'src', 'semantic', 'semanticOpIds.ts');
fs.writeFileSync(outputPath, content, 'utf8');

console.log(`✅ Generated semanticOpIds.ts with ${allOpIds.length} operation IDs\n`);
console.log('Operation IDs by domain:');

const byDomain = {};
for (const id of allOpIds) {
  const domain = id.split('.')[0];
  byDomain[domain] = (byDomain[domain] || 0) + 1;
}

for (const [domain, count] of Object.entries(byDomain).sort()) {
  console.log(`  ${domain}: ${count} operations`);
}

console.log(`\nTotal: ${allOpIds.length} operations\n`);
