/**
 * Generate comprehensive documentation for all nodes and commands
 * 
 * This script generates complete documentation for:
 * - All 193 nodes with semanticOps information
 * - All 91 commands with semantic linkages
 * 
 * Output:
 * - client/src/data/nodeDocumentation.ts
 * - client/src/data/commandDocumentation.ts
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { NODE_DEFINITIONS } from '../client/src/workflow/nodeRegistry';
import { COMMAND_DEFINITIONS } from '../client/src/commands/registry';
import { COMMAND_SEMANTICS } from '../client/src/commands/commandSemantics';
import { operationRegistry } from '../client/src/semantic/operationRegistry';

// Generate node documentation
function generateNodeDocumentation() {
  const docs: Record<string, {
    label: string;
    category: string;
    description: string;
    semanticOps?: string[];
    semanticOpDescriptions?: string[];
    inputs: Array<{ name: string; type: string; description: string; required: boolean }>;
    outputs: Array<{ name: string; type: string; description: string }>;
    parameters: Array<{ name: string; type: string; label: string; default: any; description?: string }>;
    examples?: string[];
    notes?: string[];
  }> = {};

  for (const node of NODE_DEFINITIONS) {
    const semanticOps = (node as any).semanticOps as string[] | undefined;
    const semanticOpDescriptions = semanticOps?.map(opId => {
      try {
        const op = operationRegistry.getMeta(opId);
        return op ? `${op.name}: ${op.summary}` : opId;
      } catch {
        return opId;
      }
    });

    const inputs = typeof node.inputs === 'function' ? [] : (node.inputs || []);
    const outputs = typeof node.outputs === 'function' ? [] : (node.outputs || []);
    const parameters = typeof node.parameters === 'function' ? [] : (node.parameters || []);

    docs[node.type] = {
      label: node.label,
      category: node.category,
      description: node.description || `${node.label} node`,
      semanticOps,
      semanticOpDescriptions,
      inputs: inputs.map(input => ({
        name: input.name || (input as any).key || '',
        type: input.type,
        description: input.description || '',
        required: input.required || false
      })),
      outputs: outputs.map(output => ({
        name: output.name || (output as any).key || '',
        type: output.type,
        description: output.description || ''
      })),
      parameters: parameters.map(param => ({
        name: param.name,
        type: param.type,
        label: param.label,
        default: param.default,
        description: param.description
      }))
    };
  }

  return docs;
}

// Generate command documentation
function generateCommandDocumentation() {
  const docs: Record<string, {
    label: string;
    category: string;
    description: string;
    semanticOps?: string[];
    semanticOpDescriptions?: string[];
    shortcut?: string;
    aliases?: string[];
  }> = {};

  for (const command of COMMAND_DEFINITIONS) {
    const semantic = (COMMAND_SEMANTICS as any)[command.id];
    const semanticOps = semantic?.kind === 'operation' ? semantic.ops : undefined;
    const semanticOpDescriptions = semanticOps?.map((opId: string) => {
      try {
        const op = operationRegistry.getMeta(opId);
        return op ? `${op.name}: ${op.summary}` : opId;
      } catch {
        return opId;
      }
    });

    docs[command.id] = {
      label: command.label,
      category: command.category || 'performs',
      description: command.prompt || command.label,
      semanticOps,
      semanticOpDescriptions,
      shortcut: (command as any).shortcut,
      aliases: (command as any).aliases
    };
  }

  return docs;
}

// Generate TypeScript files
function generateTypeScriptFile(
  filename: string,
  exportName: string,
  data: any
) {
  const content = `/**
 * Auto-generated comprehensive documentation
 * Generated by scripts/generateComprehensiveDocumentation.ts
 * 
 * DO NOT EDIT MANUALLY - regenerate using:
 * npm run generate:docs
 */

export const ${exportName} = ${JSON.stringify(data, null, 2)} as const;
`;

  const filepath = join(process.cwd(), 'client', 'src', 'data', filename);
  writeFileSync(filepath, content, 'utf-8');
  console.log(`✓ Generated ${filepath}`);
}

// Main
function main() {
  console.log('🔍 Generating comprehensive documentation...\n');

  console.log('📝 Generating node documentation...');
  const nodeDocs = generateNodeDocumentation();
  generateTypeScriptFile('nodeDocumentation.ts', 'NODE_DOCUMENTATION', nodeDocs);
  console.log(`  ✓ ${Object.keys(nodeDocs).length} nodes documented\n`);

  console.log('📝 Generating command documentation...');
  const commandDocs = generateCommandDocumentation();
  generateTypeScriptFile('commandDocumentation.ts', 'COMMAND_DOCUMENTATION', commandDocs);
  console.log(`  ✓ ${Object.keys(commandDocs).length} commands documented\n`);

  console.log('✨ Summary:');
  console.log(`  Nodes: ${Object.keys(nodeDocs).length}`);
  console.log(`  Commands: ${Object.keys(commandDocs).length}`);
  console.log(`  Total documentation entries: ${Object.keys(nodeDocs).length + Object.keys(commandDocs).length}`);
  console.log('\n✅ Documentation generation complete!');
}

main();
