/**
 * Semantic operation definitions for geometry analysis domain
 * 
 * This module defines semantic metadata for geometry analysis operations.
 */

import type { SemanticOpMeta } from "../semanticOp";

export const ANALYSIS_OPS: readonly SemanticOpMeta[] = [
  {
    id: "geometry.analyze.info",
    domain: "geometry",
    name: "Geometry Info",
    category: "analysis",
    tags: ["geometry", "analysis", "info", "metadata"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extracts general information about geometry (type, bounds, etc.)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.dimensions",
    domain: "geometry",
    name: "Dimensions",
    category: "analysis",
    tags: ["geometry", "analysis", "dimensions", "size"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extracts dimensional information (width, height, depth)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.volume",
    domain: "geometry",
    name: "Volume",
    category: "analysis",
    tags: ["geometry", "analysis", "volume", "mesh"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Computes volume for geometry or meshes.",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.vertices",
    domain: "geometry",
    name: "Geometry Vertices",
    category: "analysis",
    tags: ["geometry", "analysis", "vertices", "points"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extracts all vertices from geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.extentVertices",
    domain: "geometry",
    name: "Geometry Extent Vertices",
    category: "analysis",
    tags: ["geometry", "analysis", "vertices"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extracts vertex indices near a geometry extent along an axis",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.edges",
    domain: "geometry",
    name: "Geometry Edges",
    category: "analysis",
    tags: ["geometry", "analysis", "edges", "curves"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extracts all edges from geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.faces",
    domain: "geometry",
    name: "Geometry Faces",
    category: "analysis",
    tags: ["geometry", "analysis", "faces", "surfaces"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extracts all faces from geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.normals",
    domain: "geometry",
    name: "Geometry Normals",
    category: "analysis",
    tags: ["geometry", "analysis", "normals", "vectors"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extracts normal vectors from geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.controlPoints",
    domain: "geometry",
    name: "Geometry Control Points",
    category: "analysis",
    tags: ["geometry", "analysis", "control", "points", "nurbs"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extracts control points from NURBS geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.proximity3d",
    domain: "geometry",
    name: "3D Proximity",
    category: "analysis",
    tags: ["geometry", "analysis", "proximity", "distance", "3d"],
    complexity: "O(n^2)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Computes proximity between 3D geometries (O(n*m))",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.proximity2d",
    domain: "geometry",
    name: "2D Proximity",
    category: "analysis",
    tags: ["geometry", "analysis", "proximity", "distance", "2d"],
    complexity: "varies",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Computes proximity between 2D geometries",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.curveProximity",
    domain: "geometry",
    name: "Curve Proximity",
    category: "analysis",
    tags: ["geometry", "analysis", "proximity", "distance", "curve"],
    complexity: "varies",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Computes proximity between curves",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.analyze.divideSurface",
    domain: "geometry",
    name: "Divide Surface",
    category: "analysis",
    tags: ["geometry", "analysis", "surface", "mesh", "points", "vertices"],
    complexity: "O(n^2)",
    cost: "medium",
    pure: true,
    deterministic: false,
    sideEffects: [],
    summary: "Samples evenly spaced points on a mesh surface using Poisson-disk sampling",
    stable: true,
    since: "1.0.0",
  },
];
