/**
 * Semantic operation definitions for command domain
 * 
 * This module defines semantic metadata for Roslyn command operations,
 * linking UI commands to backend operations.
 */

import type { SemanticOpMeta } from "../semanticOp";

export const COMMAND_OPS: readonly SemanticOpMeta[] = [
  // === CREATION COMMANDS ===
  {
    id: "command.createPoint",
    domain: "command",
    name: "Create Point",
    category: "creation",
    tags: ["geometry", "point", "vertex"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a point at a clicked location",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createLine",
    domain: "command",
    name: "Create Line",
    category: "creation",
    tags: ["geometry", "curve", "line"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates straight line segments",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createPolyline",
    domain: "command",
    name: "Create Polyline",
    category: "creation",
    tags: ["geometry", "curve", "polyline"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a connected sequence of straight segments",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createRectangle",
    domain: "command",
    name: "Create Rectangle",
    category: "creation",
    tags: ["geometry", "curve", "rectangle", "polygon"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a four-sided closed polyline with right-angle corners",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createCircle",
    domain: "command",
    name: "Create Circle",
    category: "creation",
    tags: ["geometry", "curve", "circle", "nurbs"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a perfect circular NURBS curve",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createArc",
    domain: "command",
    name: "Create Arc",
    category: "creation",
    tags: ["geometry", "curve", "arc", "nurbs"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a circular arc segment using three-point definition",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createCurve",
    domain: "command",
    name: "Create Curve",
    category: "creation",
    tags: ["geometry", "curve", "nurbs", "freeform"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a freeform NURBS curve influenced by control points",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createPrimitive",
    domain: "command",
    name: "Create Primitive",
    category: "creation",
    tags: ["geometry", "mesh", "primitive"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a mesh primitive (box, sphere, cylinder, etc.)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createNurbsBox",
    domain: "command",
    name: "Create NURBS Box",
    category: "creation",
    tags: ["geometry", "nurbs", "box", "primitive"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a box primitive using NURBS surface representation",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createNurbsSphere",
    domain: "command",
    name: "Create NURBS Sphere",
    category: "creation",
    tags: ["geometry", "nurbs", "sphere", "primitive"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a sphere using exact NURBS surface definition",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.createNurbsCylinder",
    domain: "command",
    name: "Create NURBS Cylinder",
    category: "creation",
    tags: ["geometry", "nurbs", "cylinder", "primitive"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a cylinder using exact NURBS surface definition",
    stable: true,
    since: "1.0.0",
  },

  // === OPERATION COMMANDS ===
  {
    id: "command.boolean",
    domain: "command",
    name: "Boolean",
    category: "operation",
    tags: ["geometry", "boolean", "csg"],
    complexity: "O(n^2)",
    cost: "high",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Performs Boolean operations (union, difference, intersection) on solids",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.loft",
    domain: "command",
    name: "Loft",
    category: "operation",
    tags: ["geometry", "surface", "loft"],
    complexity: "O(n^2)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a surface by lofting through two or more curves",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.surface",
    domain: "command",
    name: "Surface",
    category: "operation",
    tags: ["geometry", "surface", "fill"],
    complexity: "O(n^2)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a surface from a closed curve",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.extrude",
    domain: "command",
    name: "Extrude",
    category: "operation",
    tags: ["geometry", "extrude", "solid"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Extrudes a profile along a direction to create a solid",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.meshMerge",
    domain: "command",
    name: "Mesh Merge",
    category: "operation",
    tags: ["geometry", "mesh", "merge"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Merges multiple meshes into a single mesh",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.meshFlip",
    domain: "command",
    name: "Mesh Flip",
    category: "operation",
    tags: ["geometry", "mesh", "flip", "normals"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Flips mesh normals (reverses face orientation)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.meshThicken",
    domain: "command",
    name: "Mesh Thicken",
    category: "operation",
    tags: ["geometry", "mesh", "thicken", "offset"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Thickens a mesh by offsetting faces along normals",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.morph",
    domain: "command",
    name: "Morph",
    category: "operation",
    tags: ["geometry", "mesh", "sculpt", "deform"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Sculpts geometry by dragging vertices",
    stable: true,
    since: "1.0.0",
  },

  // === CONVERSION COMMANDS ===
  {
    id: "command.meshConvert",
    domain: "command",
    name: "NURBS to Mesh",
    category: "conversion",
    tags: ["geometry", "nurbs", "mesh", "conversion"],
    complexity: "O(n^2)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Converts NURBS curves or surfaces to mesh",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.brepToMesh",
    domain: "command",
    name: "B-Rep to Mesh",
    category: "conversion",
    tags: ["geometry", "brep", "mesh", "conversion"],
    complexity: "O(n^2)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Converts B-Rep solids to mesh",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.meshToBrep",
    domain: "command",
    name: "Mesh to B-Rep",
    category: "conversion",
    tags: ["geometry", "mesh", "brep", "conversion"],
    complexity: "O(n^2)",
    cost: "high",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Converts meshes to B-Rep solids",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.nurbsRestore",
    domain: "command",
    name: "Mesh to NURBS",
    category: "conversion",
    tags: ["geometry", "mesh", "nurbs", "conversion"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Restores NURBS from a mesh converted from NURBS",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.interpolate",
    domain: "command",
    name: "Interpolate",
    category: "conversion",
    tags: ["geometry", "curve", "interpolate", "nurbs"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Converts polyline to smooth NURBS curve passing through vertices",
    stable: true,
    since: "1.0.0",
  },

  // === TRANSFORM COMMANDS ===
  {
    id: "command.move",
    domain: "command",
    name: "Move",
    category: "transform",
    tags: ["geometry", "transform", "translate"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Translates geometry by a vector",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.rotate",
    domain: "command",
    name: "Rotate",
    category: "transform",
    tags: ["geometry", "transform", "rotate"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Rotates geometry around an axis",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.scale",
    domain: "command",
    name: "Scale",
    category: "transform",
    tags: ["geometry", "transform", "scale"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Scales geometry by a factor",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.offset",
    domain: "command",
    name: "Offset",
    category: "transform",
    tags: ["geometry", "curve", "offset"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Offsets curves by a distance",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.mirror",
    domain: "command",
    name: "Mirror",
    category: "transform",
    tags: ["geometry", "transform", "mirror"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Mirrors geometry across a plane",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.array",
    domain: "command",
    name: "Array",
    category: "transform",
    tags: ["geometry", "transform", "array", "replicate"],
    complexity: "varies",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Replicates geometry in a pattern",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.transform",
    domain: "command",
    name: "Transform",
    category: "transform",
    tags: ["geometry", "transform", "gumball"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Transforms geometry using gumball widget",
    stable: true,
    since: "1.0.0",
  },

  // === UI COMMANDS ===
  {
    id: "command.undo",
    domain: "command",
    name: "Undo",
    category: "ui",
    tags: ["history", "undo"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["state"],
    summary: "Undoes the last action",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.redo",
    domain: "command",
    name: "Redo",
    category: "ui",
    tags: ["history", "redo"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["state"],
    summary: "Redoes the last undone action",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.copy",
    domain: "command",
    name: "Copy",
    category: "ui",
    tags: ["clipboard", "copy"],
    complexity: "O(n)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["clipboard"],
    summary: "Copies selection to clipboard",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.paste",
    domain: "command",
    name: "Paste",
    category: "ui",
    tags: ["clipboard", "paste"],
    complexity: "O(n)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["state"],
    summary: "Pastes from clipboard",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.duplicate",
    domain: "command",
    name: "Duplicate",
    category: "ui",
    tags: ["clipboard", "duplicate"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Duplicates selection in place",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.delete",
    domain: "command",
    name: "Delete",
    category: "ui",
    tags: ["edit", "delete"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["state"],
    summary: "Deletes selection",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.cancel",
    domain: "command",
    name: "Cancel",
    category: "ui",
    tags: ["control", "cancel"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["state"],
    summary: "Cancels the active command",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.confirm",
    domain: "command",
    name: "Confirm",
    category: "ui",
    tags: ["control", "confirm"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["state"],
    summary: "Confirms the active command",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.gumball",
    domain: "command",
    name: "Gumball",
    category: "ui",
    tags: ["transform", "gumball", "widget"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Activates gumball transform widget",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.focus",
    domain: "command",
    name: "Focus",
    category: "ui",
    tags: ["view", "focus", "frame"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["camera"],
    summary: "Frames the current selection",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.frameAll",
    domain: "command",
    name: "Frame All",
    category: "ui",
    tags: ["view", "frame", "all"],
    complexity: "O(n)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["camera"],
    summary: "Frames all visible geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.screenshot",
    domain: "command",
    name: "Screenshot",
    category: "ui",
    tags: ["export", "screenshot", "image"],
    complexity: "O(n)",
    cost: "medium",
    pure: false,
    deterministic: false,
    sideEffects: ["io"],
    summary: "Captures the current viewport",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.view",
    domain: "command",
    name: "View",
    category: "ui",
    tags: ["view", "camera", "preset"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["camera"],
    summary: "Switches to a preset view (top/front/right/perspective)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.camera",
    domain: "command",
    name: "Camera",
    category: "ui",
    tags: ["view", "camera", "settings"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["camera"],
    summary: "Toggles camera options",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.pivot",
    domain: "command",
    name: "Pivot",
    category: "ui",
    tags: ["transform", "pivot", "origin"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Sets the pivot point for transformations",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.orbit",
    domain: "command",
    name: "Orbit",
    category: "ui",
    tags: ["view", "camera", "orbit"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["camera"],
    summary: "Orbits the camera around the view center",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.pan",
    domain: "command",
    name: "Pan",
    category: "ui",
    tags: ["view", "camera", "pan"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["camera"],
    summary: "Pans the camera",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.zoom",
    domain: "command",
    name: "Zoom",
    category: "ui",
    tags: ["view", "camera", "zoom"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["camera"],
    summary: "Zooms the camera in/out",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.selectionFilter",
    domain: "command",
    name: "Selection Filter",
    category: "ui",
    tags: ["selection", "filter"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Changes selection filter (object/vertex/edge/face)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.cycle",
    domain: "command",
    name: "Cycle Selection",
    category: "ui",
    tags: ["selection", "cycle"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Cycles through overlapping selections",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.snapping",
    domain: "command",
    name: "Snapping",
    category: "ui",
    tags: ["snap", "grid", "precision"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Toggles snapping modes (grid/vertex/endpoint/midpoint/intersection)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.grid",
    domain: "command",
    name: "Grid",
    category: "ui",
    tags: ["grid", "units", "spacing"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Changes grid spacing/units or toggles adaptive grid",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.cplane",
    domain: "command",
    name: "C-Plane",
    category: "ui",
    tags: ["cplane", "construction", "plane"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Sets the construction plane",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.display",
    domain: "command",
    name: "Display",
    category: "ui",
    tags: ["display", "shading", "wireframe"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Switches display mode (wireframe/shaded/edges/ghosted/silhouette)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.isolate",
    domain: "command",
    name: "Isolate",
    category: "ui",
    tags: ["visibility", "isolate", "hide"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Hides/locks selection or shows all",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.outliner",
    domain: "command",
    name: "Outliner",
    category: "ui",
    tags: ["outliner", "hierarchy", "layers"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Manages groups, layers, and visibility",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.tolerance",
    domain: "command",
    name: "Tolerance",
    category: "ui",
    tags: ["tolerance", "precision", "settings"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Sets absolute and angle tolerance",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.status",
    domain: "command",
    name: "Status",
    category: "ui",
    tags: ["status", "help", "ui"],
    complexity: "O(1)",
    cost: "low",
    pure: false,
    deterministic: true,
    sideEffects: ["ui"],
    summary: "Toggles command help/status bar",
    stable: true,
    since: "1.0.0",
  },
  
  // === IMPORT/EXPORT COMMANDS ===
  {
    id: "command.import.stl",
    domain: "command",
    name: "Import STL",
    category: "io",
    tags: ["import", "stl", "mesh", "file"],
    complexity: "O(n)",
    cost: "high",
    pure: false,
    deterministic: true,
    sideEffects: ["filesystem", "state"],
    summary: "Imports geometry from an STL file",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "command.export.stl",
    domain: "command",
    name: "Export STL",
    category: "io",
    tags: ["export", "stl", "mesh", "file"],
    complexity: "O(n)",
    cost: "high",
    pure: false,
    deterministic: true,
    sideEffects: ["filesystem"],
    summary: "Exports geometry to an STL file",
    stable: true,
    since: "1.0.0",
  },
];
