/**
 * Semantic operation definitions for data domain
 * 
 * This module defines semantic metadata for data operations
 * used throughout Lingua nodes.
 */

import type { SemanticOpMeta } from '../semanticOp';

export const DATA_OPS: readonly SemanticOpMeta[] = [
  {
    id: 'data.collect',
    domain: 'data',
    name: 'Collect',
    category: 'aggregation',
    tags: ['array', 'collection', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Collects values into an array',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.flatten',
    domain: 'data',
    name: 'Flatten',
    category: 'utility',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Flattens nested arrays',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.filter',
    domain: 'data',
    name: 'Filter',
    category: 'utility',
    tags: ['array', 'iteration', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Filters array elements',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.map',
    domain: 'data',
    name: 'Map',
    category: 'utility',
    tags: ['array', 'iteration', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Maps array elements',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.reduce',
    domain: 'data',
    name: 'Reduce',
    category: 'aggregation',
    tags: ['array', 'iteration', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Reduces array to single value',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.sort',
    domain: 'data',
    name: 'Sort',
    category: 'utility',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Sorts array elements',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.unique',
    domain: 'data',
    name: 'Unique',
    category: 'utility',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Removes duplicate elements',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.length',
    domain: 'data',
    name: 'Length',
    category: 'analysis',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Returns array length',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.index',
    domain: 'data',
    name: 'Index',
    category: 'utility',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Gets element at index',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.indexOf',
    domain: 'data',
    name: 'Index Of',
    category: 'utility',
    tags: ['array', 'search', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Finds the index of an element in an array',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.partition',
    domain: 'data',
    name: 'Partition',
    category: 'utility',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Partitions an array into chunks',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.slice',
    domain: 'data',
    name: 'Slice',
    category: 'utility',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Extracts a slice of an array',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.reverse',
    domain: 'data',
    name: 'Reverse',
    category: 'utility',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Reverses an array',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.range',
    domain: 'data',
    name: 'Range',
    category: 'creation',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Generates a range of numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.linspace',
    domain: 'data',
    name: 'Linspace',
    category: 'creation',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Generates linearly spaced numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'data.repeat',
    domain: 'data',
    name: 'Repeat',
    category: 'creation',
    tags: ['array', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Repeats a value n times',
    stable: true,
    since: '1.0.0'
  }
] as const;
