/**
 * Semantic operation definitions for field operations domain
 * 
 * This module defines semantic metadata for field transformation operations.
 */

import type { SemanticOpMeta } from "../semanticOp";

export const FIELD_OPS: readonly SemanticOpMeta[] = [
  {
    id: "geometry.field.transform",
    domain: "geometry",
    name: "Field Transformation",
    category: "analysis",
    tags: ["geometry", "field", "transform"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Applies a field transformation to geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.field.movePoint",
    domain: "geometry",
    name: "Move Point",
    category: "analysis",
    tags: ["geometry", "field", "point", "transform"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Moves a point using a field",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.field.movePointByVector",
    domain: "geometry",
    name: "Move Point By Vector",
    category: "analysis",
    tags: ["geometry", "field", "point", "vector", "transform"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Moves a point by a vector field",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.field.rotateVectorAxis",
    domain: "geometry",
    name: "Rotate Vector Axis",
    category: "analysis",
    tags: ["geometry", "field", "vector", "rotate", "transform"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Rotates a vector around an axis",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.field.mirrorVector",
    domain: "geometry",
    name: "Mirror Vector",
    category: "analysis",
    tags: ["geometry", "field", "vector", "mirror", "transform"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Mirrors a vector across a plane",
    stable: true,
    since: "1.0.0",
  },
];
