/**
 * Semantic operation definitions for geometry domain
 * 
 * This module defines semantic metadata for geometry operations,
 * linking geometry nodes to backend operations.
 */

import type { SemanticOpMeta } from "../semanticOp";

export const GEOMETRY_OPS: readonly SemanticOpMeta[] = [
  // === GEOMETRY PASS-THROUGH ===
  {
    id: "geometry.mesh",
    domain: "geometry",
    name: "Mesh",
    category: "passthrough",
    tags: ["geometry", "mesh", "tessellation"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Pass-through node for mesh geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.brep",
    domain: "geometry",
    name: "B-Rep",
    category: "passthrough",
    tags: ["geometry", "brep", "solid"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Pass-through node for B-Rep geometry",
    stable: true,
    since: "1.0.0",
  },
  
  // === GEOMETRY OPERATIONS ===
  {
    id: "geometry.pointCloud",
    domain: "geometry",
    name: "Point Cloud",
    category: "creation",
    tags: ["geometry", "point", "cloud"],
    complexity: "O(n)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a point cloud from a list of points",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.fillet",
    domain: "geometry",
    name: "Fillet",
    category: "operation",
    tags: ["geometry", "fillet", "curve", "smooth"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a fillet between curves or edges",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.filletEdges",
    domain: "geometry",
    name: "Fillet Edges",
    category: "operation",
    tags: ["geometry", "fillet", "edge", "smooth"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates fillets on edges of a solid",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.offsetSurface",
    domain: "geometry",
    name: "Offset Surface",
    category: "operation",
    tags: ["geometry", "offset", "surface"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Offsets a surface by a distance",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.thickenMesh",
    domain: "geometry",
    name: "Thicken Mesh",
    category: "operation",
    tags: ["geometry", "thicken", "mesh"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Thickens a mesh by offsetting faces",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.plasticwrap",
    domain: "geometry",
    name: "Plastic Wrap",
    category: "operation",
    tags: ["geometry", "wrap", "convex", "hull"],
    complexity: "O(n log n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a convex hull around geometry",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.solid",
    domain: "geometry",
    name: "Solid",
    category: "operation",
    tags: ["geometry", "solid", "brep"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a solid from surfaces",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive",
    domain: "geometry",
    name: "Primitive",
    category: "creation",
    tags: ["geometry", "primitive", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a primitive geometry shape",
    stable: true,
    since: "1.0.0",
  },
];
