/**
 * Semantic operation definitions for math domain
 * 
 * This module defines semantic metadata for mathematical operations
 * used throughout Lingua nodes.
 */

import type { SemanticOpMeta } from '../semanticOp';

export const MATH_OPS: readonly SemanticOpMeta[] = [
  // Arithmetic operations
  {
    id: 'math.add',
    domain: 'math',
    name: 'Add',
    category: 'operator',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Adds two numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.subtract',
    domain: 'math',
    name: 'Subtract',
    category: 'operator',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Subtracts one number from another',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.multiply',
    domain: 'math',
    name: 'Multiply',
    category: 'operator',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Multiplies two numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.divide',
    domain: 'math',
    name: 'Divide',
    category: 'operator',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Divides one number by another',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.modulo',
    domain: 'math',
    name: 'Modulo',
    category: 'operator',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the remainder of division',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.power',
    domain: 'math',
    name: 'Power',
    category: 'operator',
    tags: ['arithmetic', 'exponential', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Raises a number to a power',
    stable: true,
    since: '1.0.0'
  },
  
  // Rounding operations
  {
    id: 'math.floor',
    domain: 'math',
    name: 'Floor',
    category: 'operator',
    tags: ['rounding', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Rounds down to the nearest integer',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.ceil',
    domain: 'math',
    name: 'Ceiling',
    category: 'operator',
    tags: ['rounding', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Rounds up to the nearest integer',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.round',
    domain: 'math',
    name: 'Round',
    category: 'operator',
    tags: ['rounding', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Rounds to the nearest integer',
    stable: true,
    since: '1.0.0'
  },
  
  // Unary operations
  {
    id: 'math.abs',
    domain: 'math',
    name: 'Absolute Value',
    category: 'operator',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the absolute value',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.negate',
    domain: 'math',
    name: 'Negate',
    category: 'operator',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Negates a number',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.sqrt',
    domain: 'math',
    name: 'Square Root',
    category: 'operator',
    tags: ['arithmetic', 'exponential', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the square root',
    stable: true,
    since: '1.0.0'
  },
  
  // Trigonometric operations
  {
    id: 'math.sin',
    domain: 'math',
    name: 'Sine',
    category: 'operator',
    tags: ['trigonometry', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the sine of an angle',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.cos',
    domain: 'math',
    name: 'Cosine',
    category: 'operator',
    tags: ['trigonometry', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the cosine of an angle',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.tan',
    domain: 'math',
    name: 'Tangent',
    category: 'operator',
    tags: ['trigonometry', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the tangent of an angle',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.asin',
    domain: 'math',
    name: 'Arcsine',
    category: 'operator',
    tags: ['trigonometry', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the arcsine',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.acos',
    domain: 'math',
    name: 'Arccosine',
    category: 'operator',
    tags: ['trigonometry', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the arccosine',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.atan',
    domain: 'math',
    name: 'Arctangent',
    category: 'operator',
    tags: ['trigonometry', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the arctangent',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.atan2',
    domain: 'math',
    name: 'Arctangent2',
    category: 'operator',
    tags: ['trigonometry', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the arctangent of y/x',
    stable: true,
    since: '1.0.0'
  },
  
  // Exponential and logarithmic operations
  {
    id: 'math.exp',
    domain: 'math',
    name: 'Exponential',
    category: 'operator',
    tags: ['exponential', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes e raised to a power',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.log',
    domain: 'math',
    name: 'Natural Logarithm',
    category: 'operator',
    tags: ['exponential', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the natural logarithm',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.log10',
    domain: 'math',
    name: 'Base-10 Logarithm',
    category: 'operator',
    tags: ['exponential', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the base-10 logarithm',
    stable: true,
    since: '1.0.0'
  },
  
  // Aggregation operations
  {
    id: 'math.min',
    domain: 'math',
    name: 'Minimum',
    category: 'aggregation',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Returns the smaller of two numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.max',
    domain: 'math',
    name: 'Maximum',
    category: 'aggregation',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Returns the larger of two numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.clamp',
    domain: 'math',
    name: 'Clamp',
    category: 'utility',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Clamps a value between min and max',
    stable: true,
    since: '1.0.0'
  },
  
  // Interpolation operations
  {
    id: 'math.lerp',
    domain: 'math',
    name: 'Linear Interpolation',
    category: 'utility',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Linearly interpolates between two values',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.remap',
    domain: 'math',
    name: 'Remap',
    category: 'utility',
    tags: ['arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Remaps a value from one range to another',
    stable: true,
    since: '1.0.0'
  },
  
  // Comparison operations
  {
    id: 'math.equal',
    domain: 'math',
    name: 'Equal',
    category: 'operator',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Checks if two numbers are equal',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.notEqual',
    domain: 'math',
    name: 'Not Equal',
    category: 'operator',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Checks if two numbers are not equal',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.lessThan',
    domain: 'math',
    name: 'Less Than',
    category: 'operator',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Checks if one number is less than another',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.lessThanOrEqual',
    domain: 'math',
    name: 'Less Than or Equal',
    category: 'operator',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Checks if one number is less than or equal to another',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.greaterThan',
    domain: 'math',
    name: 'Greater Than',
    category: 'operator',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Checks if one number is greater than another',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.greaterThanOrEqual',
    domain: 'math',
    name: 'Greater Than or Equal',
    category: 'operator',
    tags: ['comparison', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Checks if one number is greater than or equal to another',
    stable: true,
    since: '1.0.0'
  },
  
  // Random operations
  {
    id: 'math.random',
    domain: 'math',
    name: 'Random',
    category: 'utility',
    tags: ['arithmetic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: false,
    deterministic: false,
    sideEffects: ['random'],
    summary: 'Generates a random number',
    stable: true,
    since: '1.0.0'
  },
  
  // Statistics operations
  {
    id: 'math.sum',
    domain: 'math',
    name: 'Sum',
    category: 'statistics',
    tags: ['statistics', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the sum of an array of numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.average',
    domain: 'math',
    name: 'Average',
    category: 'statistics',
    tags: ['statistics', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the average of an array of numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.median',
    domain: 'math',
    name: 'Median',
    category: 'statistics',
    tags: ['statistics', 'pure', 'deterministic'],
    complexity: 'O(n log n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    summary: 'Computes the median of an array of numbers',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'math.stdDev',
    domain: 'math',
    name: 'Standard Deviation',
    category: 'statistics',
    tags: ['statistics', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the standard deviation of an array of numbers',
    stable: true,
    since: '1.0.0'
  },
  
  // Expression operations
  {
    id: 'math.expression',
    domain: 'math',
    name: 'Expression',
    category: 'utility',
    tags: ['expression', 'pure', 'deterministic'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    summary: 'Evaluates a mathematical expression',
    stable: true,
    since: '1.0.0'
  }
] as const;
