/**
 * Semantic operation definitions for primitive geometry domain
 * 
 * This module defines semantic metadata for primitive shape operations.
 */

import type { SemanticOpMeta } from "../semanticOp";

export const PRIMITIVE_OPS: readonly SemanticOpMeta[] = [
  {
    id: "geometry.primitive.cylinder",
    domain: "geometry",
    name: "Cylinder",
    category: "primitive",
    tags: ["geometry", "primitive", "cylinder", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a cylindrical primitive with specified radius and height",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.torus",
    domain: "geometry",
    name: "Torus",
    category: "primitive",
    tags: ["geometry", "primitive", "torus", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a toroidal primitive with major and minor radii",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.pyramid",
    domain: "geometry",
    name: "Pyramid",
    category: "primitive",
    tags: ["geometry", "primitive", "pyramid", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a pyramidal primitive with square base",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.tetrahedron",
    domain: "geometry",
    name: "Tetrahedron",
    category: "primitive",
    tags: ["geometry", "primitive", "tetrahedron", "platonic", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a tetrahedral primitive (4 faces, Platonic solid)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.octahedron",
    domain: "geometry",
    name: "Octahedron",
    category: "primitive",
    tags: ["geometry", "primitive", "octahedron", "platonic", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates an octahedral primitive (8 faces, Platonic solid)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.icosahedron",
    domain: "geometry",
    name: "Icosahedron",
    category: "primitive",
    tags: ["geometry", "primitive", "icosahedron", "platonic", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates an icosahedral primitive (20 faces, Platonic solid)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.dodecahedron",
    domain: "geometry",
    name: "Dodecahedron",
    category: "primitive",
    tags: ["geometry", "primitive", "dodecahedron", "platonic", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a dodecahedral primitive (12 faces, Platonic solid)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.hemisphere",
    domain: "geometry",
    name: "Hemisphere",
    category: "primitive",
    tags: ["geometry", "primitive", "hemisphere", "sphere", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a hemispherical primitive (half sphere)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.capsule",
    domain: "geometry",
    name: "Capsule",
    category: "primitive",
    tags: ["geometry", "primitive", "capsule", "pill", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a capsule primitive (cylinder with hemispherical caps)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.disk",
    domain: "geometry",
    name: "Disk",
    category: "primitive",
    tags: ["geometry", "primitive", "disk", "circle", "2d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a circular disk primitive",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.ring",
    domain: "geometry",
    name: "Ring",
    category: "primitive",
    tags: ["geometry", "primitive", "ring", "annulus", "2d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a ring primitive (annulus with inner and outer radii)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.triangularPrism",
    domain: "geometry",
    name: "Triangular Prism",
    category: "primitive",
    tags: ["geometry", "primitive", "prism", "triangular", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a triangular prism primitive",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.hexagonalPrism",
    domain: "geometry",
    name: "Hexagonal Prism",
    category: "primitive",
    tags: ["geometry", "primitive", "prism", "hexagonal", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a hexagonal prism primitive",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.pentagonalPrism",
    domain: "geometry",
    name: "Pentagonal Prism",
    category: "primitive",
    tags: ["geometry", "primitive", "prism", "pentagonal", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a pentagonal prism primitive",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.torusKnot",
    domain: "geometry",
    name: "Torus Knot",
    category: "primitive",
    tags: ["geometry", "primitive", "torus", "knot", "3d"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a torus knot primitive with p and q parameters",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.utahTeapot",
    domain: "geometry",
    name: "Utah Teapot",
    category: "primitive",
    tags: ["geometry", "primitive", "teapot", "utah", "3d", "classic"],
    complexity: "O(1)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates the classic Utah teapot primitive",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.frustum",
    domain: "geometry",
    name: "Frustum",
    category: "primitive",
    tags: ["geometry", "primitive", "frustum", "truncated", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a frustum primitive (truncated pyramid or cone)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.mobiusStrip",
    domain: "geometry",
    name: "Mobius Strip",
    category: "primitive",
    tags: ["geometry", "primitive", "mobius", "strip", "topology", "3d"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a Mobius strip primitive (non-orientable surface)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.ellipsoid",
    domain: "geometry",
    name: "Ellipsoid",
    category: "primitive",
    tags: ["geometry", "primitive", "ellipsoid", "sphere", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates an ellipsoidal primitive with three radii",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.wedge",
    domain: "geometry",
    name: "Wedge",
    category: "primitive",
    tags: ["geometry", "primitive", "wedge", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a wedge primitive (triangular prism)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.sphericalCap",
    domain: "geometry",
    name: "Spherical Cap",
    category: "primitive",
    tags: ["geometry", "primitive", "spherical", "cap", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a spherical cap primitive (portion of sphere)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.bipyramid",
    domain: "geometry",
    name: "Bipyramid",
    category: "primitive",
    tags: ["geometry", "primitive", "bipyramid", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a bipyramid primitive (two pyramids base-to-base)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.rhombicDodecahedron",
    domain: "geometry",
    name: "Rhombic Dodecahedron",
    category: "primitive",
    tags: ["geometry", "primitive", "rhombic", "dodecahedron", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a rhombic dodecahedron primitive (Catalan solid)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.truncatedCube",
    domain: "geometry",
    name: "Truncated Cube",
    category: "primitive",
    tags: ["geometry", "primitive", "truncated", "cube", "archimedean", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a truncated cube primitive (Archimedean solid)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.truncatedOctahedron",
    domain: "geometry",
    name: "Truncated Octahedron",
    category: "primitive",
    tags: ["geometry", "primitive", "truncated", "octahedron", "archimedean", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a truncated octahedron primitive (Archimedean solid)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.truncatedIcosahedron",
    domain: "geometry",
    name: "Truncated Icosahedron",
    category: "primitive",
    tags: ["geometry", "primitive", "truncated", "icosahedron", "archimedean", "soccer", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a truncated icosahedron primitive (soccer ball, Archimedean solid)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.pipe",
    domain: "geometry",
    name: "Pipe",
    category: "primitive",
    tags: ["geometry", "primitive", "pipe", "tube", "3d"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a pipe primitive (hollow cylinder)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.superellipsoid",
    domain: "geometry",
    name: "Superellipsoid",
    category: "primitive",
    tags: ["geometry", "primitive", "superellipsoid", "superquadric", "3d"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a superellipsoid primitive with exponent parameters",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.hyperbolicParaboloid",
    domain: "geometry",
    name: "Hyperbolic Paraboloid",
    category: "primitive",
    tags: ["geometry", "primitive", "hyperbolic", "paraboloid", "saddle", "3d"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a hyperbolic paraboloid primitive (saddle surface)",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.geodesicDome",
    domain: "geometry",
    name: "Geodesic Dome",
    category: "primitive",
    tags: ["geometry", "primitive", "geodesic", "dome", "buckminster", "3d"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a geodesic dome primitive with frequency parameter",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "geometry.primitive.oneSheetHyperboloid",
    domain: "geometry",
    name: "One-Sheet Hyperboloid",
    category: "primitive",
    tags: ["geometry", "primitive", "hyperboloid", "ruled", "3d"],
    complexity: "O(n)",
    cost: "medium",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Creates a one-sheet hyperboloid primitive (ruled surface)",
    stable: true,
    since: "1.0.0",
  },
];
