/**
 * Semantic operation definitions for solver domain
 * 
 * This module defines semantic metadata for solver operations
 * used throughout Lingua nodes.
 */

import type { SemanticOpMeta } from '../semanticOp';

export const SOLVER_OPS: readonly SemanticOpMeta[] = [
  {
    id: 'solver.physics',
    domain: 'solver',
    name: 'Physics Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'equilibrium'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Solves structural mechanics simulation with force equilibrium',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.chemistry',
    domain: 'solver',
    name: 'Chemistry Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'distribution'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['state', 'random'],
    summary: 'Solves material distribution simulation with particle dynamics',
    stable: true,
    since: '1.0.0'
  },

  {
    id: 'solver.evolutionary',
    domain: 'solver',
    name: 'Evolutionary Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'optimization'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['state', 'random'],
    summary: 'Solves optimization problems using genetic algorithms',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.voxel',
    domain: 'solver',
    name: 'Voxel Solver',
    category: 'conversion',
    tags: ['3d', 'discrete'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Converts geometry to voxel field representation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.topologyOptimization',
    domain: 'solver',
    name: 'Topology Optimization Solver',
    category: 'utility',
    tags: ['3d', 'optimization', 'structural', 'simp', 'marching-cubes'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Optimizes material layout for structural performance using SIMP and marching cubes',
    stable: true,
    since: '2.0.0'
  },
  // Internal simulator operations (not directly exposed to nodes)
  {
    id: 'simulator.initialize',
    domain: 'solver',
    name: 'Initialize Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Initializes simulation state (internal implementation detail)',
    stable: true,
    since: '1.0.0',
    internal: true
  },
  {
    id: 'simulator.step',
    domain: 'solver',
    name: 'Step Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Executes single simulation step (internal implementation detail)',
    stable: true,
    since: '1.0.0',
    internal: true
  },
  {
    id: 'simulator.converge',
    domain: 'solver',
    name: 'Check Convergence',
    category: 'analysis',
    tags: ['simulation', 'internal'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks simulation convergence criteria (internal implementation detail)',
    stable: true,
    since: '1.0.0',
    internal: true
  },
  {
    id: 'simulator.finalize',
    domain: 'solver',
    name: 'Finalize Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Finalizes simulation and generates output (internal implementation detail)',
    stable: true,
    since: '1.0.0',
    internal: true
  },

  // Voxel Simulator Operations
  {
    id: 'simulator.voxel.initialize',
    domain: 'solver',
    name: 'Initialize Voxel Simulator',
    category: 'utility',
    tags: ['simulation', 'voxel', 'grid'],
    complexity: 'O(1)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Prepares voxel grid bounds and resolution',
    stable: true,
    since: '2.0.0'
  },
  {
    id: 'simulator.voxel.step',
    domain: 'solver',
    name: 'Voxelize Geometry',
    category: 'conversion',
    tags: ['simulation', 'voxel', 'discretization'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Samples geometry occupancy into a voxel grid',
    stable: true,
    since: '2.0.0'
  },
  {
    id: 'simulator.voxel.finalize',
    domain: 'solver',
    name: 'Finalize Voxel Simulator',
    category: 'utility',
    tags: ['simulation', 'voxel', 'mesh'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Generates voxel mesh and statistics',
    stable: true,
    since: '2.0.0'
  },

  // Topology Simulator Operations (internal implementation details)
  {
    id: 'simulator.topology.initialize',
    domain: 'solver',
    name: 'Initialize Topology Simulator',
    category: 'utility',
    tags: ['simulation', 'topology', 'optimization', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Initializes SIMP density field and topology constraints (internal)',
    stable: true,
    since: '2.0.0',
    internal: true
  },
  {
    id: 'simulator.topology.step',
    domain: 'solver',
    name: 'Step Topology Simulator',
    category: 'utility',
    tags: ['simulation', 'topology', 'optimization', 'internal'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Executes one SIMP optimization iteration (internal)',
    stable: true,
    since: '2.0.0',
    internal: true
  },
  {
    id: 'simulator.topology.converge',
    domain: 'solver',
    name: 'Check Topology Convergence',
    category: 'analysis',
    tags: ['simulation', 'topology', 'optimization', 'internal'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks topology optimization convergence criteria (internal)',
    stable: true,
    since: '2.0.0',
    internal: true
  },
  {
    id: 'simulator.topology.finalize',
    domain: 'solver',
    name: 'Finalize Topology Simulator',
    category: 'utility',
    tags: ['simulation', 'topology', 'geometry', 'internal'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Extracts and registers topology geometry from the density field (internal)',
    stable: true,
    since: '2.0.0',
    internal: true
  },
  {
    id: 'simulator.topology.preview',
    domain: 'solver',
    name: 'Preview Topology Geometry',
    category: 'analysis',
    tags: ['simulation', 'topology', 'analysis', 'view', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Builds lightweight preview geometry during simulation (internal)',
    stable: true,
    since: '2.1.0',
    internal: true
  },
  {
    id: 'simulator.topology.sync',
    domain: 'solver',
    name: 'Sync Topology Geometry',
    category: 'io',
    tags: ['simulation', 'topology', 'state', 'display', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Synchronizes preview geometry into Roslyn viewport (internal)',
    stable: true,
    since: '2.1.0',
    internal: true
  },
  {
    id: 'simulator.topology.pause',
    domain: 'solver',
    name: 'Pause Topology Simulator',
    category: 'utility',
    tags: ['simulation', 'topology', 'control', 'internal'],
    complexity: 'O(1)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Pauses topology optimization iteration loop (internal)',
    stable: true,
    since: '2.1.0',
    internal: true
  },
  {
    id: 'simulator.topology.resume',
    domain: 'solver',
    name: 'Resume Topology Simulator',
    category: 'utility',
    tags: ['simulation', 'topology', 'control', 'internal'],
    complexity: 'O(1)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Resumes topology optimization iteration loop (internal)',
    stable: true,
    since: '2.1.0',
    internal: true
  },
  {
    id: 'simulator.topology.reset',
    domain: 'solver',
    name: 'Reset Topology Simulator',
    category: 'utility',
    tags: ['simulation', 'topology', 'control', 'internal'],
    complexity: 'O(1)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Resets topology simulation state and clears outputs (internal)',
    stable: true,
    since: '2.1.0',
    internal: true
  },
  {
    id: 'simulator.topology.plasticwrap',
    domain: 'solver',
    name: 'Plasticwrap Topology Geometry',
    category: 'utility',
    tags: ['simulation', 'topology', 'geometry', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Applies plasticwrap smoothing pass to topology output (internal)',
    stable: true,
    since: '2.1.0',
    internal: true
  },
  {
    id: 'simulator.topology.stabilityGuard',
    domain: 'solver',
    name: 'Topology Stability Guard',
    category: 'analysis',
    tags: ['simulation', 'topology', 'analysis', 'control', 'internal'],
    complexity: 'O(1)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Escalates convergence strategy when FE solver stalls repeatedly (internal)',
    stable: true,
    since: '2.1.0',
    internal: true
  },
  
  // Chemistry Simulator Operations
  {
    id: 'simulator.chemistry.initialize',
    domain: 'solver',
    name: 'Initialize Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'particles'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state', 'random'],
    summary: 'Initializes particle system for chemistry simulation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.step',
    domain: 'solver',
    name: 'Step Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'particles'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Executes single particle simulation step with SPH dynamics',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.converge',
    domain: 'solver',
    name: 'Check Chemistry Convergence',
    category: 'analysis',
    tags: ['simulation', 'chemistry'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks energy convergence for material distribution',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.finalize',
    domain: 'solver',
    name: 'Finalize Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'voxel'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Generates voxel field and mesh from particle distribution',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.blendMaterials',
    domain: 'solver',
    name: 'Blend Materials',
    category: 'utility',
    tags: ['chemistry', 'materials'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Blends materials at particle level using diffusion',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.evaluateGoals',
    domain: 'solver',
    name: 'Evaluate Chemistry Goals',
    category: 'analysis',
    tags: ['chemistry', 'goals'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Evaluates goal satisfaction for material distribution',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.analyze',
    domain: 'solver',
    name: 'Analyze Chemistry Simulation',
    category: 'analysis',
    tags: ['chemistry', 'analysis'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Builds diagnostics, convergence, and distribution analysis for chemistry outputs',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.validate',
    domain: 'solver',
    name: 'Validate Chemistry Simulation',
    category: 'analysis',
    tags: ['chemistry', 'analysis'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Validates chemistry outputs for constraints and conservation checks',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.computeGradients',
    domain: 'solver',
    name: 'Compute Chemistry Gradients',
    category: 'analysis',
    tags: ['chemistry', 'field', 'vector'],
    complexity: 'O(n)',
    cost: 'high',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Computes gradient fields for material optimization analysis',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.computeStatistics',
    domain: 'solver',
    name: 'Compute Chemistry Statistics',
    category: 'analysis',
    tags: ['chemistry', 'statistics'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Computes particle and field statistics for chemistry diagnostics',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.checkConservation',
    domain: 'solver',
    name: 'Check Chemistry Conservation',
    category: 'analysis',
    tags: ['chemistry', 'analysis', 'physics'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks mass, energy, and momentum conservation for chemistry simulation',
    stable: true,
    since: '1.0.0'
  },
  
  // Physics Simulator Operations
  {
    id: 'simulator.physics.initialize',
    domain: 'solver',
    name: 'Initialize Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'fea'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Initializes FEA system for physics simulation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.step',
    domain: 'solver',
    name: 'Step Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'fea'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Executes single solver iteration for structural analysis',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.converge',
    domain: 'solver',
    name: 'Check Physics Convergence',
    category: 'analysis',
    tags: ['simulation', 'physics'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks force/displacement convergence for equilibrium',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.finalize',
    domain: 'solver',
    name: 'Finalize Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'stress'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Generates stress field and deformed geometry',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.applyLoads',
    domain: 'solver',
    name: 'Apply Loads',
    category: 'utility',
    tags: ['physics', 'forces'],
    complexity: 'O(n)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Applies forces and constraints to structural system',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.computeStress',
    domain: 'solver',
    name: 'Compute Stress Field',
    category: 'utility',
    tags: ['physics', 'stress'],
    complexity: 'O(n)',
    cost: 'high',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Computes stress field from displacement solution',
    stable: true,
    since: '1.0.0'
  },
  
  // Voxel Solver Operations
  {
    id: 'solver.voxel.voxelize',
    domain: 'solver',
    name: 'Voxelize Geometry',
    category: 'conversion',
    tags: ['voxel', 'discretization', '3d'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Converts geometry to voxel grid representation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.voxel.extractIsosurface',
    domain: 'solver',
    name: 'Extract Isosurface',
    category: 'conversion',
    tags: ['voxel', 'isosurface', 'marching-cubes'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Extracts mesh isosurface from voxel field using marching cubes',
    stable: true,
    since: '1.0.0'
  },
  
  // Topology Optimization Solver Operations
  {
    id: 'solver.topologyOptimization.optimize',
    domain: 'solver',
    name: 'Optimize Topology',
    category: 'analysis',
    tags: ['topology', 'optimization', 'structural'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Optimizes material layout for structural performance',
    stable: true,
    since: '1.0.0'
  }
] as const;
