/**
 * Semantic operation definitions for solver domain
 * 
 * This module defines semantic metadata for solver operations
 * used throughout Lingua nodes.
 */

import type { SemanticOpMeta } from '../semanticOp';

export const SOLVER_OPS: readonly SemanticOpMeta[] = [
  {
    id: 'solver.physics',
    domain: 'solver',
    name: 'Physics Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'equilibrium'],
    complexity: 'O(n*iterations)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['geometry', 'state'],
    summary: 'Solves structural mechanics simulation with force equilibrium',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.chemistry',
    domain: 'solver',
    name: 'Chemistry Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'distribution'],
    complexity: 'O(n*iterations)',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['geometry', 'state', 'random'],
    summary: 'Solves material distribution simulation with particle dynamics',
    stable: true,
    since: '1.0.0'
  },

  {
    id: 'solver.evolutionary',
    domain: 'solver',
    name: 'Evolutionary Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'optimization'],
    complexity: 'O(population*generations)',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['geometry', 'state', 'random'],
    summary: 'Solves optimization problems using genetic algorithms',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.voxel',
    domain: 'solver',
    name: 'Voxel Solver',
    category: 'conversion',
    tags: ['3d', 'discrete'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Converts geometry to voxel field representation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.topologyOptimization',
    domain: 'solver',
    name: 'Topology Optimization Solver',
    category: 'utility',
    tags: ['3d', 'optimization', 'structural'],
    complexity: 'O(n*iterations)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['geometry', 'state'],
    summary: 'Optimizes material layout for structural performance',
    stable: false,
    since: '2.0.0'
  },
  {
    id: 'simulator.initialize',
    domain: 'solver',
    name: 'Initialize Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Initializes simulation state',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.step',
    domain: 'solver',
    name: 'Step Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Executes single simulation step',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.converge',
    domain: 'solver',
    name: 'Check Convergence',
    category: 'query',
    tags: ['simulation', 'internal'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks simulation convergence criteria',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.finalize',
    domain: 'solver',
    name: 'Finalize Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['geometry'],
    summary: 'Finalizes simulation and generates output',
    stable: true,
    since: '1.0.0'
  },
  
  // Chemistry Simulator Operations
  {
    id: 'simulator.chemistry.initialize',
    domain: 'solver',
    name: 'Initialize Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'particles'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state', 'random'],
    summary: 'Initializes particle system for chemistry simulation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.step',
    domain: 'solver',
    name: 'Step Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'particles'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Executes single particle simulation step with SPH dynamics',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.converge',
    domain: 'solver',
    name: 'Check Chemistry Convergence',
    category: 'query',
    tags: ['simulation', 'chemistry'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks energy convergence for material distribution',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.finalize',
    domain: 'solver',
    name: 'Finalize Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'voxel'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['geometry'],
    summary: 'Generates voxel field and mesh from particle distribution',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.blendMaterials',
    domain: 'solver',
    name: 'Blend Materials',
    category: 'utility',
    tags: ['chemistry', 'materials'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Blends materials at particle level using diffusion',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.evaluateGoals',
    domain: 'solver',
    name: 'Evaluate Chemistry Goals',
    category: 'query',
    tags: ['chemistry', 'goals'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Evaluates goal satisfaction for material distribution',
    stable: true,
    since: '1.0.0'
  },
  
  // Physics Simulator Operations
  {
    id: 'simulator.physics.initialize',
    domain: 'solver',
    name: 'Initialize Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'fea'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Initializes FEA system for physics simulation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.step',
    domain: 'solver',
    name: 'Step Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'fea'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Executes single solver iteration for structural analysis',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.converge',
    domain: 'solver',
    name: 'Check Physics Convergence',
    category: 'query',
    tags: ['simulation', 'physics'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks force/displacement convergence for equilibrium',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.finalize',
    domain: 'solver',
    name: 'Finalize Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'stress'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['geometry'],
    summary: 'Generates stress field and deformed geometry',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.applyLoads',
    domain: 'solver',
    name: 'Apply Loads',
    category: 'utility',
    tags: ['physics', 'forces'],
    complexity: 'O(n)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Applies forces and constraints to structural system',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.computeStress',
    domain: 'solver',
    name: 'Compute Stress Field',
    category: 'utility',
    tags: ['physics', 'stress'],
    complexity: 'O(n)',
    cost: 'high',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Computes stress field from displacement solution',
    stable: true,
    since: '1.0.0'
  }
] as const;
