/**
 * Semantic operation definitions for solver domain
 * 
 * This module defines semantic metadata for solver operations
 * used throughout Lingua nodes.
 */

import type { SemanticOpMeta } from '../semanticOp';

export const SOLVER_OPS: readonly SemanticOpMeta[] = [
  {
    id: 'solver.physics',
    domain: 'solver',
    name: 'Physics Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'equilibrium'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Solves structural mechanics simulation with force equilibrium',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.chemistry',
    domain: 'solver',
    name: 'Chemistry Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'distribution'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['state', 'random'],
    summary: 'Solves material distribution simulation with particle dynamics',
    stable: true,
    since: '1.0.0'
  },

  {
    id: 'solver.evolutionary',
    domain: 'solver',
    name: 'Evolutionary Solver',
    category: 'utility',
    tags: ['3d', 'simulation', 'optimization'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['state', 'random'],
    summary: 'Solves optimization problems using genetic algorithms',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.voxel',
    domain: 'solver',
    name: 'Voxel Solver',
    category: 'conversion',
    tags: ['3d', 'discrete'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Converts geometry to voxel field representation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.topologyOptimization',
    domain: 'solver',
    name: 'Topology Optimization Solver',
    category: 'utility',
    tags: ['3d', 'optimization', 'structural'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Optimizes material layout for structural performance',
    stable: false,
    since: '2.0.0'
  },
  {
    id: 'simulator.initialize',
    domain: 'solver',
    name: 'Initialize Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Initializes simulation state',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.step',
    domain: 'solver',
    name: 'Step Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Executes single simulation step',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.converge',
    domain: 'solver',
    name: 'Check Convergence',
    category: 'analysis',
    tags: ['simulation', 'internal'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks simulation convergence criteria',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.finalize',
    domain: 'solver',
    name: 'Finalize Simulator',
    category: 'utility',
    tags: ['simulation', 'internal'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Finalizes simulation and generates output',
    stable: true,
    since: '1.0.0'
  },
  
  // Chemistry Simulator Operations
  {
    id: 'simulator.chemistry.initialize',
    domain: 'solver',
    name: 'Initialize Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'particles'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state', 'random'],
    summary: 'Initializes particle system for chemistry simulation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.step',
    domain: 'solver',
    name: 'Step Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'particles'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Executes single particle simulation step with SPH dynamics',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.converge',
    domain: 'solver',
    name: 'Check Chemistry Convergence',
    category: 'analysis',
    tags: ['simulation', 'chemistry'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks energy convergence for material distribution',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.finalize',
    domain: 'solver',
    name: 'Finalize Chemistry Simulator',
    category: 'utility',
    tags: ['simulation', 'chemistry', 'voxel'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Generates voxel field and mesh from particle distribution',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.blendMaterials',
    domain: 'solver',
    name: 'Blend Materials',
    category: 'utility',
    tags: ['chemistry', 'materials'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: false,
    sideEffects: ['state'],
    summary: 'Blends materials at particle level using diffusion',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.evaluateGoals',
    domain: 'solver',
    name: 'Evaluate Chemistry Goals',
    category: 'analysis',
    tags: ['chemistry', 'goals'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Evaluates goal satisfaction for material distribution',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.analyze',
    domain: 'solver',
    name: 'Analyze Chemistry Simulation',
    category: 'analysis',
    tags: ['chemistry', 'analysis'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Builds diagnostics, convergence, and distribution analysis for chemistry outputs',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.validate',
    domain: 'solver',
    name: 'Validate Chemistry Simulation',
    category: 'analysis',
    tags: ['chemistry', 'validation'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Validates chemistry outputs for constraints and conservation checks',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.computeGradients',
    domain: 'solver',
    name: 'Compute Chemistry Gradients',
    category: 'analysis',
    tags: ['chemistry', 'gradients'],
    complexity: 'O(n)',
    cost: 'high',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Computes gradient fields for material optimization analysis',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.computeStatistics',
    domain: 'solver',
    name: 'Compute Chemistry Statistics',
    category: 'analysis',
    tags: ['chemistry', 'statistics'],
    complexity: 'O(n)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Computes particle and field statistics for chemistry diagnostics',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.chemistry.checkConservation',
    domain: 'solver',
    name: 'Check Chemistry Conservation',
    category: 'analysis',
    tags: ['chemistry', 'conservation'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks mass, energy, and momentum conservation for chemistry simulation',
    stable: true,
    since: '1.0.0'
  },
  
  // Physics Simulator Operations
  {
    id: 'simulator.physics.initialize',
    domain: 'solver',
    name: 'Initialize Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'fea'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Initializes FEA system for physics simulation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.step',
    domain: 'solver',
    name: 'Step Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'fea'],
    complexity: 'O(n)',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Executes single solver iteration for structural analysis',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.converge',
    domain: 'solver',
    name: 'Check Physics Convergence',
    category: 'analysis',
    tags: ['simulation', 'physics'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Checks force/displacement convergence for equilibrium',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.finalize',
    domain: 'solver',
    name: 'Finalize Physics Simulator',
    category: 'utility',
    tags: ['simulation', 'physics', 'stress'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Generates stress field and deformed geometry',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.applyLoads',
    domain: 'solver',
    name: 'Apply Loads',
    category: 'utility',
    tags: ['physics', 'forces'],
    complexity: 'O(n)',
    cost: 'low',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Applies forces and constraints to structural system',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'simulator.physics.computeStress',
    domain: 'solver',
    name: 'Compute Stress Field',
    category: 'utility',
    tags: ['physics', 'stress'],
    complexity: 'O(n)',
    cost: 'high',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Computes stress field from displacement solution',
    stable: true,
    since: '1.0.0'
  },
  
  // Voxel Solver Operations
  {
    id: 'solver.voxel.voxelize',
    domain: 'solver',
    name: 'Voxelize Geometry',
    category: 'conversion',
    tags: ['voxel', 'discretization', '3d'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Converts geometry to voxel grid representation',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'solver.voxel.extractIsosurface',
    domain: 'solver',
    name: 'Extract Isosurface',
    category: 'conversion',
    tags: ['voxel', 'isosurface', 'marching-cubes'],
    complexity: 'O(n)',
    cost: 'medium',
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: 'Extracts mesh isosurface from voxel field using marching cubes',
    stable: true,
    since: '1.0.0'
  },
  
  // Topology Optimization Solver Operations
  {
    id: 'solver.topologyOptimization.optimize',
    domain: 'solver',
    name: 'Optimize Topology',
    category: 'analysis',
    tags: ['topology', 'optimization', 'structural'],
    complexity: 'varies',
    cost: 'high',
    pure: false,
    deterministic: true,
    sideEffects: ['state'],
    summary: 'Optimizes material layout for structural performance',
    stable: true,
    since: '1.0.0'
  }
] as const;
