/**
 * Semantic operation definitions for vector domain
 * 
 * This module defines semantic metadata for vector operations
 * used throughout Lingua nodes.
 */

import type { SemanticOpMeta } from '../semanticOp';

export const VECTOR_OPS: readonly SemanticOpMeta[] = [
  {
    id: 'vector.add',
    domain: 'vector',
    name: 'Vector Add',
    category: 'operator',
    tags: ['vector3', 'arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Adds two vectors',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.subtract',
    domain: 'vector',
    name: 'Vector Subtract',
    category: 'operator',
    tags: ['vector3', 'arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Subtracts one vector from another',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.multiply',
    domain: 'vector',
    name: 'Vector Multiply',
    category: 'operator',
    tags: ['vector3', 'arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Multiplies a vector by a scalar',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.divide',
    domain: 'vector',
    name: 'Vector Divide',
    category: 'operator',
    tags: ['vector3', 'arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Divides a vector by a scalar',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.dot',
    domain: 'vector',
    name: 'Dot Product',
    category: 'operator',
    tags: ['vector3', 'arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the dot product of two vectors',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.cross',
    domain: 'vector',
    name: 'Cross Product',
    category: 'operator',
    tags: ['vector3', 'arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the cross product of two vectors',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.normalize',
    domain: 'vector',
    name: 'Normalize',
    category: 'utility',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Normalizes a vector to unit length',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.length',
    domain: 'vector',
    name: 'Length',
    category: 'analysis',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the length of a vector',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.distance',
    domain: 'vector',
    name: 'Distance',
    category: 'analysis',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the distance between two points',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.lerp',
    domain: 'vector',
    name: 'Vector Lerp',
    category: 'utility',
    tags: ['vector3', 'arithmetic', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Linearly interpolates between two vectors',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.construct',
    domain: 'vector',
    name: 'Construct Vector',
    category: 'utility',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Constructs a vector from x, y, z components',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.deconstruct',
    domain: 'vector',
    name: 'Deconstruct Vector',
    category: 'utility',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Deconstructs a vector into x, y, z components',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.angle',
    domain: 'vector',
    name: 'Vector Angle',
    category: 'analysis',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Computes the angle between two vectors',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.project',
    domain: 'vector',
    name: 'Vector Project',
    category: 'utility',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Projects one vector onto another',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.attractor',
    domain: 'vector',
    name: 'Point Attractor',
    category: 'analysis',
    tags: ['vector3', 'field', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Creates an attractor field from a point',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.constant.origin',
    domain: 'vector',
    name: 'Origin',
    category: 'primitive',
    tags: ['vector3', 'constant', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Returns the origin vector (0, 0, 0)',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.constant.unitX',
    domain: 'vector',
    name: 'Unit X',
    category: 'primitive',
    tags: ['vector3', 'constant', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Returns the unit X vector (1, 0, 0)',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.constant.unitY',
    domain: 'vector',
    name: 'Unit Y',
    category: 'primitive',
    tags: ['vector3', 'constant', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Returns the unit Y vector (0, 1, 0)',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.constant.unitZ',
    domain: 'vector',
    name: 'Unit Z',
    category: 'primitive',
    tags: ['vector3', 'constant', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Returns the unit Z vector (0, 0, 1)',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.constant.unitXYZ',
    domain: 'vector',
    name: 'Unit XYZ',
    category: 'primitive',
    tags: ['vector3', 'constant', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Returns the unit XYZ vector (1, 1, 1)',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.moveVector',
    domain: 'vector',
    name: 'Move Vector',
    category: 'utility',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Creates a movement vector from two points',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.scaleVector',
    domain: 'vector',
    name: 'Scale Vector',
    category: 'utility',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Creates a scale vector from a scalar or components',
    stable: true,
    since: '1.0.0'
  },
  {
    id: 'vector.fromPoints',
    domain: 'vector',
    name: 'Vector From Points',
    category: 'utility',
    tags: ['vector3', 'pure', 'deterministic'],
    complexity: 'O(1)',
    cost: 'low',
    pure: true,
    deterministic: true,
    summary: 'Creates a vector from two points (end - start)',
    stable: true,
    since: '1.0.0'
  }
] as const;
