/**
 * Semantic operation definitions for wave function domain
 * 
 * This module defines semantic metadata for wave function operations.
 */

import type { SemanticOpMeta } from "../semanticOp";

export const WAVE_OPS: readonly SemanticOpMeta[] = [
  {
    id: "math.wave.sine",
    domain: "math",
    name: "Sine Wave",
    category: "wave",
    tags: ["math", "wave", "sine", "periodic"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Generates a sine wave function",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "math.wave.cosine",
    domain: "math",
    name: "Cosine Wave",
    category: "wave",
    tags: ["math", "wave", "cosine", "periodic"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Generates a cosine wave function",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "math.wave.sawtooth",
    domain: "math",
    name: "Sawtooth Wave",
    category: "wave",
    tags: ["math", "wave", "sawtooth", "periodic"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Generates a sawtooth wave function",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "math.wave.triangle",
    domain: "math",
    name: "Triangle Wave",
    category: "wave",
    tags: ["math", "wave", "triangle", "periodic"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Generates a triangle wave function",
    stable: true,
    since: "1.0.0",
  },
  {
    id: "math.wave.square",
    domain: "math",
    name: "Square Wave",
    category: "wave",
    tags: ["math", "wave", "square", "periodic"],
    complexity: "O(1)",
    cost: "low",
    pure: true,
    deterministic: true,
    sideEffects: [],
    summary: "Generates a square wave function",
    stable: true,
    since: "1.0.0",
  },
];
